config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get 'tesutokari/index' => 'tesutokari#index'
  get 'students/index' => 'students#index'
  get 'students1' => 'students1#index'
  get 'students1/new' => 'students1#new'
  get 'tweets' => 'tweets#index'
  get 'students/link' => 'students#link'
  get 'tweets/new' => 'tweets#new'
  post 'tweets' => 'tweets#create'
  root 'students#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/students1.rb
class Students1 < ApplicationRecord
end

app/models/tweet.rb
class Tweet < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/students1_controller.rb
class Students1Controller < ApplicationController
    def index
    end
    def new
        @students1 = Student1.new
      end
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
    def index
    end
    def link
    end
end

app/controllers/tesutokari_controller.rb
class TesutokariController < ApplicationController
    def index
    end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
    def index
    end
    def new
        @tweet = Tweet.new
      end
      def create
        tweet = Tweet.new(tweet_params)
        if tweet.save
          redirect_to :action => "index"
        else
          redirect_to :action => "new"
        end
      end
    
      private
      def tweet_params
        params.require(:tweet).permit(:body)
      end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/students1_helper.rb
module Students1Helper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/helpers/tesutokari_helper.rb
module TesutokariHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Question</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/students/index.html.erb
やっほ
<%= link_to 'ここを押してね！', :controller => "students", :action => "link" %>

app/views/students/link.html.erb
My name is GeekSalon.
<%= link_to 'トップページ', students_index_path %>
<%= link_to '一覧表示', students1_path %>

app/views/students1/index.html.erb
Enjoy programming!

app/views/tesutokari/index.html.erb
やっほ

app/views/tweets/index.html.erb
Enjoy programming!
<%= link_to "新規投稿ページへ", tweets_new_path %>

app/views/tweets/new.html.erb
<h1>GeekTwitter</h1>
<h3>新規Tweet</h3>
<%= form_for @tweet do |f| %>
  <div class="field">
    <%= f.label :body %>
    <%= f.text_field :body, :size => 140 %>
  </div>
  <%= f.submit "Tweetする" %>
<% end %>
<%= link_to "Tweet一覧に戻る", tweets_path %>